name: Create Release

on:
  workflow_dispatch:
    inputs:
      is_draft:
        description: '建立為草稿'
        type: boolean
        default: false
        required: false
      is_pre:
        description: '發布為測試版'
        type: boolean
        default: false
        required: false

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    # Add explicit permissions for releases
    permissions:
      contents: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      
      - name: Install dependencies
        run: npm install
      
      - name: Ensure no code issue
        run: npm run lint
      
      - name: Build extension
        run: npm run build
      
      - name: Get version from manifest.json
        id: get_version
        run: |
          echo "VERSION=$(node -p "require('./src/manifest.json').version")" >> $GITHUB_OUTPUT
      
      - name: Create version tag
        id: create_tag
        run: |
          VERSION=${{ steps.get_version.outputs.VERSION }}
          echo "TAG_NAME=v${VERSION}" >> $GITHUB_OUTPUT
      
      - name: Create Git Tag
        run: |
          git tag ${{ steps.create_tag.outputs.TAG_NAME }}
          git push origin ${{ steps.create_tag.outputs.TAG_NAME }}
      
      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.create_tag.outputs.TAG_NAME }}
          draft: ${{ github.event.inputs.is_draft }}
          prerelease: ${{ github.event.inputs.is_pre }}
          make_latest: 'legacy'  # mark latest for a release with larger version
          generate_release_notes: true
          files: dist/ditto_vpn-${{ steps.get_version.outputs.VERSION }}.zip
