name: Create Release and Publish

on:
  workflow_dispatch:
    inputs:
      is_draft:
        description: '建立為草稿'
        type: boolean
        default: false
      is_pre:
        description: '發布為測試版'
        type: boolean
        default: false

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    # Add explicit permissions for releases
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Ensure no code issue
        run: npm run lint

      - name: Build extension
        run: npm run build

      - name: Get version from manifest.json
        id: get_version
        run: |
          VERSION=$(node -p "require('./src/manifest.json').version")
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "TAG_NAME=v$VERSION" >> $GITHUB_OUTPUT
          echo "FILE_PATH=dist/ditto_vpn-$VERSION.zip" >> $GITHUB_OUTPUT

      - name: Create Git Tag
        run: |
          git tag ${{ steps.get_version.outputs.TAG_NAME }}
          git push origin ${{ steps.get_version.outputs.TAG_NAME }}

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.get_version.outputs.TAG_NAME }}
          draft: ${{ github.event.inputs.is_draft }}
          prerelease: ${{ github.event.inputs.is_pre }}
          make_latest: 'legacy'  # mark latest for a release with larger version
          generate_release_notes: true
          files: ${{ steps.get_version.outputs.FILE_PATH }}

      - name: Upload to Chrome Web Store
        if: ${{ github.event.inputs.is_pre == 'false' }}
        uses: mnao305/chrome-extension-upload@v5.0.0
        with:
          publish: ${{ github.event.inputs.is_draft == 'false' }}
          file-path: ${{ steps.get_version.outputs.FILE_PATH }}
          extension-id: ${{ vars.CHROME_EXTENSION_ID }}

          # https://github.com/fregante/chrome-webstore-upload-keys
          client-id: ${{ secrets.CHROME_CLIENT_ID }}
          client-secret: ${{ secrets.CHROME_CLIENT_SECRET }}
          refresh-token: ${{ secrets.CHROME_REFRESH_TOKEN }}
