name: Create Release and Publish

on:
  workflow_dispatch:
    inputs:
      is_draft:
        description: '建立為草稿'
        type: boolean
        default: false
      is_pre:
        description: '發布為測試版'
        type: boolean
        default: false

jobs:
  build-and-release:
    name: Build and Release
    runs-on: ubuntu-latest
    environment: production
    env:
      IS_DRAFT: ${{ github.event.inputs.is_draft }}
      IS_PRE: ${{ github.event.inputs.is_pre }}
      TIMEZONE: ${{ vars.TIMEZONE || 'UTC' }}

    # Add explicit permissions for tag/release
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure and verify
        run: |
          VERSION=$(jq -r '.version' './src/manifest.json')

          if [ "$IS_PRE" = "false" ]; then
            EXPECTED_LINE="## [$VERSION] - $(TZ="$TIMEZONE" date +%Y-%m-%d)"
            if ! grep -Fxq "$EXPECTED_LINE" CHANGELOG.md; then
              echo "❌ Missing expected changelog line: $EXPECTED_LINE"
              exit 1
            fi
          fi

          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "TAG_NAME=v$VERSION" >> $GITHUB_ENV
          echo "EXT_PATH=dist/ditto_vpn-$VERSION.zip" >> $GITHUB_ENV

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Verify no code issue
        run: npm run lint

      - name: Build extension
        run: npm run build

      - name: Create Git Tag
        run: |
          git tag --force ${{ env.TAG_NAME }}
          git push origin ${{ env.TAG_NAME }}

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG_NAME }}
          draft: ${{ env.IS_DRAFT }}
          prerelease: ${{ env.IS_PRE }}
          make_latest: 'legacy'  # mark latest for a release with larger version
          generate_release_notes: true
          files: ${{ env.EXT_PATH }}

      - name: Upload to Chrome Web Store
        if: ${{ ! cancelled() && steps.create_release.conclusion == 'success' && env.IS_PRE == 'false' }}
        uses: mnao305/chrome-extension-upload@v5.0.0
        with:
          publish: ${{ env.IS_DRAFT == 'false' }}
          file-path: ${{ env.EXT_PATH }}
          extension-id: ${{ vars.CHROME_EXTENSION_ID }}

          # https://github.com/fregante/chrome-webstore-upload-keys
          client-id: ${{ secrets.CHROME_CLIENT_ID }}
          client-secret: ${{ secrets.CHROME_CLIENT_SECRET }}
          refresh-token: ${{ secrets.CHROME_REFRESH_TOKEN }}

      - name: Upload to Microsoft Edge Add-ons
        if: ${{ ! cancelled() && steps.create_release.conclusion == 'success' && env.IS_PRE == 'false' }}
        uses: wdzeng/edge-addon@v2
        with:
          upload-only: ${{ env.IS_DRAFT == 'true' }}
          zip-path: ${{ env.EXT_PATH }}
          product-id: ${{ vars.EDGE_PRODUCT_ID }}
          client-id: ${{ secrets.EDGE_CLIENT_ID }}
          api-key: ${{ secrets.EDGE_API_KEY }}
